# SPDX-License-Identifier: Apache-2.0
# Kbuild — TPT GPU DRM kernel module

obj-$(CONFIG_DRM_TPT_GPU) += tpt_gpu.o

tpt_gpu-objs := \
	src/lib.rs \
	src/device.rs \
	src/gem.rs \
	src/regs.rs

# Enable Rust for this module.
tpt_gpu-$(CONFIG_RUST) := y
